-- ==========================================
-- SCRIPT DE MIGRACIÓN: M.A.S. ACCESORIOS (SUPABASE)
-- ==========================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLAS BASE (Sin dependencias externas)

CREATE TABLE contactos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    identificacion VARCHAR(100),
    telefono VARCHAR(100),
    email VARCHAR(255),
    tipo VARCHAR(50) DEFAULT 'cliente',
    estado VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE productos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sku VARCHAR(100) UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    costo_base NUMERIC(15, 2) DEFAULT 0,
    precio_venta NUMERIC(15, 2) DEFAULT 0,
    stock_minimo INTEGER DEFAULT 5,
    estado VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cuentas_bancarias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) DEFAULT 'cash',
    saldo_inicial NUMERIC(15, 2) DEFAULT 0,
    estado VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABLAS DEPENDIENTES (Con Foreign Keys)

CREATE TABLE facturas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero BIGINT UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    vencimiento DATE,
    contacto_id BIGINT REFERENCES contactos(id) ON DELETE RESTRICT,
    total NUMERIC(15, 2) DEFAULT 0,
    estado VARCHAR(50) DEFAULT 'open',
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE factura_detalles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    factura_id BIGINT REFERENCES facturas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(15, 2) NOT NULL DEFAULT 0,
    descuento_porcentaje NUMERIC(5, 2) DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0
);

CREATE TABLE cotizaciones (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero BIGINT UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    vencimiento DATE,
    contacto_id BIGINT REFERENCES contactos(id) ON DELETE RESTRICT,
    total NUMERIC(15, 2) DEFAULT 0,
    estado VARCHAR(50) DEFAULT 'draft',
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cotizacion_detalles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cotizacion_id BIGINT REFERENCES cotizaciones(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(15, 2) NOT NULL DEFAULT 0,
    descuento_porcentaje NUMERIC(5, 2) DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0
);

CREATE TABLE pagos_ingresos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero BIGINT UNIQUE,
    fecha DATE NOT NULL,
    monto NUMERIC(15, 2) NOT NULL,
    cuenta_id BIGINT REFERENCES cuentas_bancarias(id) ON DELETE RESTRICT,
    contacto_id BIGINT REFERENCES contactos(id) ON DELETE RESTRICT,
    factura_id BIGINT REFERENCES facturas(id) ON DELETE SET NULL,
    tipo VARCHAR(50) DEFAULT 'in',
    estado VARCHAR(50) DEFAULT 'open',
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lotes_fifo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    cantidad_inicial INTEGER NOT NULL,
    cantidad_actual INTEGER NOT NULL,
    costo_unitario NUMERIC(15, 2) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    referencia VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. POLÍTICAS DE SEGURIDAD (Row Level Security - RLS)

-- Habilitar RLS en todas las tablas
ALTER TABLE contactos ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE cuentas_bancarias ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE factura_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cotizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE cotizacion_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos_ingresos ENABLE ROW LEVEL SECURITY;
ALTER TABLE lotes_fifo ENABLE ROW LEVEL SECURITY;

-- Crear políticas para permitir acceso CRUD SÓLO a usuarios autenticados
-- NOTA: auth.uid() devuelve el ID del usuario en Supabase Auth

CREATE POLICY "acceso_autenticado_contactos" ON contactos FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_productos" ON productos FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_cuentas" ON cuentas_bancarias FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_facturas" ON facturas FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_factura_det" ON factura_detalles FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_cotizaciones" ON cotizaciones FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_cotizacion_det" ON cotizacion_detalles FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_pagos" ON pagos_ingresos FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "acceso_autenticado_lotes" ON lotes_fifo FOR ALL USING (auth.uid() IS NOT NULL);
